# Generated by Django 5.1.4 on 2024-12-18 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0004_alter_comments_signature'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comments',
            new_name='Comment',
        ),
    ]
